CREATE TABLE IF NOT EXISTS users (
	u_id INT NOT NULL PRIMARY KEY,
	u_name VARCHAR(100) NOT NULL
);

INSERT INTO users VALUES(1, 'Ioan');
INSERT INTO users VALUES(2, 'Faye');

CREATE TABLE IF NOT EXISTS cars (
	c_id INT NOT NULL PRIMARY KEY,
	c_name VARCHAR(100) NOT NULL
);

INSERT INTO cars VALUES(1, 'Tesla');
INSERT INTO cars VALUES(2, 'Toyota');

CREATE TABLE IF NOT EXISTS user_to_car (
	u_id INT NOT NULL PRIMARY KEY,
	c_id INT NOT NULL FOREIGN KEY-- FIX
);